#!/bin/bash
# dont run this unless you want to experience freeeeeeeeeeeeeeze
declare -a arr=("-a=loss=squared_loss,fit_intercept=True,shuffle=True"
                "-a=loss=huber,fit_intercept=True,shuffle=True"
                "-a=loss=epsilon_insensitive,fit_intercept=True,shuffle=True"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=True,shuffle=True"
                "-a=loss=squared_loss,fit_intercept=False,shuffle=True"
                "-a=loss=huber,fit_intercept=False,shuffle=True"
                "-a=loss=epsilon_insensitive,fit_intercept=False,shuffle=True"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=False,shuffle=True"
                "-a=loss=squared_loss,fit_intercept=True,shuffle=True"
                "-a=loss=huber,fit_intercept=True,shuffle=True"
                "-a=loss=epsilon_insensitive,fit_intercept=True,shuffle=True"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=True,shuffle=True"
                "-a=loss=squared_loss,fit_intercept=False,shuffle=True"
                "-a=loss=huber,fit_intercept=False,shuffle=True"
                "-a=loss=epsilon_insensitive,fit_intercept=False,shuffle=True"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=False,shuffle=True"
                "-a=loss=squared_loss,fit_intercept=True,shuffle=True -u"
                "-a=loss=huber,fit_intercept=True,shuffle=True -u"
                "-a=loss=epsilon_insensitive,fit_intercept=True,shuffle=True -u"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=True,shuffle=True -u"
                "-a=loss=squared_loss,fit_intercept=False,shuffle=True -u"
                "-a=loss=huber,fit_intercept=False,shuffle=True -u"
                "-a=loss=epsilon_insensitive,fit_intercept=False,shuffle=True -u"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=False,shuffle=True -u"
                "-a=loss=squared_loss,fit_intercept=True,shuffle=True -u"
                "-a=loss=huber,fit_intercept=True,shuffle=True -u"
                "-a=loss=epsilon_insensitive,fit_intercept=True,shuffle=True -u"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=True,shuffle=True -u"
                "-a=loss=squared_loss,fit_intercept=False,shuffle=True -u"
                "-a=loss=huber,fit_intercept=False,shuffle=True -u"
                "-a=loss=epsilon_insensitive,fit_intercept=False,shuffle=True -u"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=squared_loss,fit_intercept=True,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=huber,fit_intercept=True,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=epsilon_insensitive,fit_intercept=True,shuffle=True -u  -f=method,url,payload_size"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=True,shuffle=True -u"
                "-a=loss=squared_loss,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=huber,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=epsilon_insensitive,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=False,shuffle=True -u"
                "-a=loss=squared_loss,fit_intercept=True,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=huber,fit_intercept=True,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=epsilon_insensitive,fit_intercept=True,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=True,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=squared_loss,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=huber,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=epsilon_insensitive,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                "-a=loss=squared_epsilon_insensitive,fit_intercept=False,shuffle=True -u -f=method,url,payload_size"
                )

mkdir -p "results"
for i in "${arr[@]}"
do
   echo "$i"
   touch "results/sgd_$i"
   python src/limython.py -n=3 -l=10000 -m=sgd -r=false -p=best-counter -k=10 $i > "results/sgd_$i" &
done
