#!/bin/bash
# dont run this unless you want to experience freeeeeeeeeeeeeeze
declare -a arr=("-a=criterion=mae,splitter=best,max_depth=20,max_features=auto"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=auto"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=auto"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=auto"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=sqrt"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=sqrt"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=sqrt"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=sqrt"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=log2"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=log2"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=log2"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=log2"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=auto -u=true"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=auto -u=true"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=auto -u=true"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=auto -u=true"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=sqrt -u=true"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=sqrt -u=true"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=sqrt -u=true"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=sqrt -u=true"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=log2 -u=true"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=log2 -u=true"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=log2 -u=true"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=log2 -u=true"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=auto -u=true  -f=method,url,payload_size"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=auto -u=true  -f=method,url,payload_size"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=auto -u=true  -f=method,url,payload_size"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=auto -u=true  -f=method,url,payload_size"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=sqrt -u=true  -f=method,url,payload_size"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=sqrt -u=true  -f=method,url,payload_size"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=sqrt -u=true  -f=method,url,payload_size"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=sqrt -u=true  -f=method,url,payload_size"
                "-a=criterion=mae,splitter=best,max_depth=20,max_features=log2 -u=true  -f=method,url,payload_size"
                "-a=criterion=mse,splitter=best,max_depth=20,max_features=log2 -u=true  -f=method,url,payload_size"
                "-a=criterion=mae,splitter=random,max_depth=20,max_features=log2 -u=true  -f=method,url,payload_size"
                "-a=criterion=mse,splitter=random,max_depth=20,max_features=log2 -u  -f=method,url,payload_size=true"
                )

mkdir -p "results"
for i in "${arr[@]}"
do
   echo "$i"
   touch "results/tree_$i"
   python src/limython.py -n=3 -l=10000 -m=tree -r=false -p=best-counter -k=10 $i > "results/tree_$i" &
done
